### ISSUE TITLE
About the introgression detect using hyde

### ISSUE THREAD

**Issue by Jhe1004** [pblischak/HyDe#16]
Hi @pblischak ,

HyDe software is very helpful to us, very thankful.

I already know that hyde is very useful in the detection of hybrid species. However, If the hybridization does not result in the formation of a new lineage, It can be detected with HyDe?

Thanks,
JianHe

**Comment by pblischak** [comment]
Hi JianHe -- I'm glad HyDe has been useful for your work!

A recent paper from Kong and Kubatko ([Comparative Performance of Popular Methods for Hybrid Detection using Genomic Data](https://doi.org/10.1093/sysbio/syaa092)) has a really nice simulation study evaluating HyDe's performance in scenarios that involve introgression rather than hybrid speciation. From their results, it does look like HyDe can be used in these cases of hybridization without the formation of a new lineage

**Comment by Jhe1004** [comment]
Thanks @pblischak !

**Comment by pblischak** [comment]
You're welcome! Let me know if you have any other questions
