### ISSUE TITLE
Not all triples evaluated

### ISSUE THREAD

**Issue by SheaML** [pblischak/HyDe#3]
Hi Paul,

I'm using a freshly cloned version of HyDe from today (8/30/2017), and I'm noticing that something seems to be off with the results from run_hyde.py. 

For example, in one case I'm using 9 taxa, but my output file contains only 112 rows of results, and one taxon in particular doesn't seem to be evaluated as a hybrid at all. This taxon is also giving odd results when used as a parent (Gamma = 0 anytime it is used as parent1, Gamma=-nan & p=0.5 anytime it is used as parent2). I don't see anything odd about this taxon in my datafile, though.

Please let me know if you'd like me to send you the results and input files.

Thanks,
Shea

**Comment by pblischak** [comment]
Hi Shea,

The only reason a particular triple wouldn't be included in the output is if the hypothesis test produces an incompatible value for testing. The program automatically looks for this and doesn't print the results if this is the case. It usually happens when there isn't a lot of data and when there is very little evidence for hybridization. If you want to send the results and your data files I'd be happy to take a look at them. If you won't mind, I also have a couple questions for you about your data:

- How many sites are you working with?
- How much missing data do you have?
- Do you have multiple individuals per population?

Hopefully that helps but let me know if anything else is unclear.

**Comment by SheaML** [comment]
Hi Paul,

Gotcha - I'll close the issue since it doesn't seem to be a bug. 

I am working with ~500,000 sites (ddRAD data), ~10-20% missing data, and multiple individuals. I'll do some more tests on my side and then send you my data if I'm still confused -- Thanks.

Shea
